任务一

In [2]:
import cv2

img = cv2.imread('H:/DeepLearning/img/img.jpg')  # 读取图片

cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 640, 360)
cv2.imshow('img', img)  # 显示图片

while 1:
    key = cv2.waitKey(0)
    if key == ord('q') or key == 27:  # 读取键盘按键‘q’或‘Esc’
        cv2.destroyAllWindows()  # 摧毁所有窗口
        break

任务二

In [2]:
import cv2

img = cv2.imread('H:/DeepLearning/img/img.jpg')  # 读取图片

img_down = cv2.pyrDown(img)
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_normal = cv2.normalize(img,None,0,100,cv2.NORM_MINMAX)#归一化

cv2.imshow('img', img)  # 显示图片
cv2.imshow('img_down', img_down)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_normal', img_normal) 
while 1:
    key = cv2.waitKey(0)
    if key == ord('q') or key == 27:  # 读取键盘按键‘q’或‘Esc’
        cv2.destroyAllWindows()  # 摧毁所有窗口
        break

In [3]:
import cv2
import numpy as np

img = cv2.imread('H:/DeepLearning/img/img.jpg')
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(np.shape(img))
print(img)
print(np.shape(img_gray))
print(img_gray)

(360, 640, 3)
[[[ 76  79  93]
  [ 76  79  93]
  [ 76  79  93]
  ...
  [ 95 101 106]
  [ 94 100 107]
  [ 94 100 107]]

 [[ 75  78  92]
  [ 75  78  92]
  [ 76  79  93]
  ...
  [ 95 101 106]
  [ 94 100 107]
  [ 94 100 107]]

 [[ 73  79  92]
  [ 73  79  92]
  [ 73  79  90]
  ...
  [ 94 100 105]
  [ 94 100 107]
  [ 94 100 107]]

 ...

 [[ 97  93 105]
  [ 98  94 106]
  [ 99  95 106]
  ...
  [112 102 108]
  [109  99 105]
  [107  97 103]]

 [[ 96  94 106]
  [ 96  94 106]
  [ 97  96 106]
  ...
  [112 105 108]
  [111 104 107]
  [109 102 105]]

 [[ 96  94 106]
  [ 97  95 107]
  [ 98  97 107]
  ...
  [112 105 108]
  [113 106 109]
  [112 105 108]]]
(360, 640)
[[ 83  83  83 ... 102 101 101]
 [ 82  82  83 ... 102 101 101]
 [ 82  82  82 ... 101 101 101]
 ...
 [ 97  98  99 ... 105 102 100]
 [ 98  98  99 ... 107 106 104]
 [ 98  99 100 ... 107 108 107]]
